export enum Config {
  MAX_STATUS = '14',
  ICON_BIOGRAFIA = 'fas book-open',
  NAME_BIOGRAFIA = 'WINK.ITEM_TYPES.BIOGRAPHY',
  NAME_GENDER = 'WINK.ITEM_TYPES.SEX',
  ICON_GENDER = 'fas genderless',
  NAME_AGE = 'WINK.ITEM_TYPES.AGE',
  YEARS = 'WINK.ITEM_TYPES.YEARS',
  ICON_AGE = 'fas calendar-day',
  GENDER_HIDEEN = 3,
  SOCIAL_NETWORK = 'redessociales',
  BIRTHDAY = 'fechadenacimiento',
  NICKNAME = 'apodo',
  ADDRESS = 'direccion',
  CUSTOM = 'personalizado',
  AVATAR = 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y',
  IMAGE_JPEG = 'image/jpeg',
  NO_REQUESTS = 'WINK.WINKS.EMPTY.REQUESTS',
  NO_RECORD = 'WINK.WINKS.EMPTY.RECORD',
  NO_ITEMS = 'WINK.PRIVATE_PROFILES.ITEMS_EMPTY',
}
